### ISSUE TITLE
Is this library production ready (yet)?

### ISSUE THREAD

**Issue by Hadryan** [kaltura/media-framework#101]
I see the current release version is [v1.7.3](https://github.com/kaltura/media-framework/releases/tag/v1.7.3). So, I conclude that it's a mature library (according to Semantic Versioning). However, it seems many different parts of this library change on a daily basis. Is there any release roadmap?

**Comment by erankor** [comment]
We are using it on production for the last ~2 years, and we ran many large-scale webcasts on the platform, so the general answer is - yes! However, as you rightfully mentioned, it is in active development, so naturally some parts are less mature than others.
For example, LLHLS is not used by any of our customers yet, and it's currently being validated by our QA team.

**Comment by erankor** [comment]
Thank you for the kind words :)
