### ISSUE TITLE
libsrt.so.1.5: cannot open shared object 

### ISSUE THREAD

**Issue by barmaglot92** [kaltura/media-framework#156]
After doing all steps in conf when running nginx it cant find this lib

/usr/local/nginx/sbin/nginx: error while loading shared libraries: libsrt.so.1.5: cannot open shared object file: No such file or directory

file exists
ls /usr/local/lib/libsrt.so.1.5
/usr/local/lib/libsrt.so.1.5

seems we need specify --modules-path=/usr/local/lib or put libsrt.so.1.5 in /usr/local/nginx/modules

**Comment by erankor** [comment]
Probably just need to run `sudo ldconfig`

**Comment by barmaglot92** [comment]
> 

thank you

**Comment by erankor** [comment]
Thanks, pushed #157
