### ISSUE TITLE
Problem during the build the transcoder image

### ISSUE THREAD

**Issue by Leeaandrob** [kaltura/media-framework#162]
# Steps to reproduce:

Following the README.md in this link https://github.com/kaltura/media-framework/tree/master/conf when you are building the second image `https://github.com/kaltura/media-framework/tree/master/conf` a problem happen one line 23 https://github.com/kaltura/media-framework/blob/master/transcoder/Dockerfile#L23

**Comment by erankor** [comment]
Thanks @Leeaandrob, merged #163 now, this line referenced some folder that was removed from the project.
