### ISSUE TITLE
Issue with RTMP stream

### ISSUE THREAD

**Issue by 5centscdn** [kaltura/media-framework#168]
We used the sample nginx.conf file in the conf folder to test RTMP and HLS livestreaming.

I am able to publish streams using OBS and FFMPEG. However, the stream stops and disconnects after 28 seconds.

Here is the FFMPEG command I used for testing:

ffmpeg -re -i rtmp://10.0.0.1:1935/test/live -codec copy -f flv rtmp://206.75.162.236/live/livestream6

Here are the error logs from Nginx:

2023/07/13 22:01:52 [error] 30496#30496: *3 ngx_rtmp_kmp_idle: closing idle connection, client: 51.91.66.224, server: 0.0.0.0:1935
2023/07/13 22:03:13 [error] 30496#30496: *8 ngx_rtmp_kmp_idle: closing idle connection, client: 51.91.66.224, server: 0.0.0.0:1935

How can I solve this issue?

Thank you in advance.

**Comment by erankor** [comment]
This error means that no video/audio packet was received on the socket for 30 seconds, if you want to disable this functionality, you can set `kmp_idle_timeout` to 0 in nginx conf (or set it to a higher value like 10m).
