### ISSUE TITLE
Issue in HLS delivery

### ISSUE THREAD

**Issue by 5centscdn** [kaltura/media-framework#169]
Hello there,

I have been testing the Kaltura Media Framework for the last few days. We have successfully published the streams, but we are unable to play either HLS or DASH streams. Could you please provide the correct playback URL syntax? We are currently using the sample nginx.conf file in the conf directory and following the instructions in this documentation: "https://github.com/kaltura/media-framework/tree/master/conf". However, we are encountering an issue where the streams are not playing, and we are receiving a 404 error.

**FFMPEG command for publishing:**

ffmpeg -re -i a.mp4 -c copy -f flv "rtmp://localhost:1935/live/ch1_s1"

**HLS URL tried:**

curl -i http://localhost/clear/ch/ch1/master.m3u8
HTTP/1.1 404 Not Found
Server: nginx/1.25.2
Date: Thu, 20 Jul 2023 23:51:37 GMT
Content-Type: text/html
Content-Length: 153
Connection: keep-alive

**We have also tried below URLs too:**

http://localhost/clear/ch1/s1/master.m3u8
http://localhost/clear/ch1_s1/master.m3u8

**Error Log**
==========
2023/07/20 23:50:26 [info] 20214#20214: *536 client connected '127.0.0.1'
2023/07/20 23:50:27 [info] 20214#20214: *536 connect: app='live' args='' flashver='FMLE/3.0 (compatible; Lavf57.83.100)' swf_url='' tc_url='rtmp://localhost:1935/live' page_url='' acodecs=0 vcodecs=0 object_encoding=0, client: 127.0.0.1, server: 0.0.0.0:1935
2023/07/20 23:50:27 [info] 20214#20214: *536 FCPublish: name='ch1_s1', client: 127.0.0.1, server: 0.0.0.0:1935
2023/07/20 23:50:27 [info] 20214#20214: *536 createStream, client: 127.0.0.1, server: 0.0.0.0:1935
2023/07/20 23:50:27 [info] 20214#20214: *536 publish: name='ch1_s1' args='' type=live silent=0, client: 127.0.0.1, server: 0.0.0.0:1935
2023/07/20 23:50:34 [error] 20214#20214: *539 ngx_http_live_ksmp_output_error_str: unknown channel "ch1", code: 10, client: 127.0.0.1, server: , request: "GET /ksmp/?channel_id=ch1&timeline_id=main&flags=2a10010a HTTP/1.0", host: "127.0.0.1:8001"
2023/07/20 23:50:34 [error] 20214#20214: *537 ngx_http_pckg_core_post_handler: ksmp error, code: 10, msg: "unknown channel "ch1"" while sending to client, client: 127.0.0.1, server: _, request: "GET /clear/ch/ch1/master.m3u8 HTTP/1.1", subrequest: "/ksmp_proxy/", upstream: "http://127.0.0.1:8001/ksmp/?channel_id=ch1&timeline_id=main&flags=2a10010a", host: "localhost"
2023/07/20 23:50:34 [info] 20214#20214: *537 client 127.0.0.1 closed keepalive connection

**Access Log**
==========
127.0.0.1 - - [20/Jul/2023:23:51:37 +0000] "GET /ksmp/?channel_id=ch1&timeline_id=main&flags=2a10010a HTTP/1.0" 200 230 0.000 "-" "curl/7.58.0" "127.0.0.1:8001" 149 20214 543
127.0.0.1 - - [20/Jul/2023:23:51:37 +0000] "GET /clear/ch/ch1/master.m3u8 HTTP/1.1" 404 308 0.000 "-" "curl/7.58.0" "localhost" 97 20214 541
127.0.0.1 [20/Jul/2023:23:51:45 +0000] PUBLISH "live" "ch1_s1" "" - 1248733 519 "" "FMLE/3.0 (compatible; Lavf57.83.100)" (20s)

**Nginx conf: https://demo-test.5centscdn.com/nginx.conf**

How can I solve this issue?

Thank you in advance.

**Comment by erankor** [comment]
Based on the previous issue you opened (disconnect due to idle timeout), I would guess that no frames are being published... If that is the case, the rtmp module does not send the 'publish' notification and no channel is created. Maybe the codecs of the mp4 you are testing with are not compatible with rtmp protocol? 
Anyway, a few things you can do to debug -
1. Enable debug log (need to compile `--with-debug` and set `error_log` in nginx conf to debug)
2. You can curl the status endpoints of the media-framework modules, for example - `http://localhost:8001/api/live/` returns all the channels that exist on the live segmenter, you can check there whether the channel exists or not.

**Comment by 5centscdn** [comment]
Hello,

>> Maybe the codecs of the mp4 you are testing with are not compatible with rtmp protocol?

We hare testing with the sample file from kaltura. The file is: http://cdnapi.kaltura.com/p/2035982/playManifest/entryId/0_w4l3m87h/flavorId/0_vsu1xutk/format/download/a.mp4

FFMPEG command used: ffmpeg -re -i a.mp4 -c copy -f flv "rtmp://localhost:1935/live/ch1_s1"

>> status endpoints

curl -i http://localhost:8001/api/live/
HTTP/1.1 200 OK
Server: nginx/1.25.2
Date: Fri, 21 Jul 2023 19:05:52 GMT
Content-Type: application/json
Content-Length: 429
Connection: keep-alive

{"version":"0.1","nginx_version":"1.25.2","compiler":"gcc 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04) ","built":"Jul 18 2023 21:46:21","pid":12375,"time":1689966352,"uptime":511,"store":{"s3":{"dummy_bucket":{"read":{"started":0,"error":0,"success":0,"success_msec":0,"success_size":0},"write":{"started":0,"error":0,"success":0,"success_msec":0,"success_size":0}}}},"zombie_input_bufs":{"size":0,"count":0,"lock_count":0},"channels":{}}

>> debug log

2023/07/21 19:33:31 [debug] 20015#20015: worker cycle
2023/07/21 19:33:31 [debug] 20015#20015: epoll timer: 73
2023/07/21 19:33:31 [debug] 20015#20015: epoll: fd:3 ev:0001 d:000055A21DEA76C0
2023/07/21 19:33:31 [debug] 20015#20015: *3 recv: eof:0, avail:-1
2023/07/21 19:33:31 [debug] 20015#20015: *3 recv: fd:3 3704 of 3704
2023/07/21 19:33:31 [debug] 20015#20015: *3 recv: avail:4984
2023/07/21 19:33:31 [debug] 20015#20015: *3 RTMP recv video (9) csid=6 timestamp=24303 mlen=91290 msid=1 nbufs=23 real_mlen=91290
2023/07/21 19:33:31 [debug] 20015#20015: *3 ngx_rtmp_kmp_av: no context
2023/07/21 19:33:31 [debug] 20015#20015: *3 RTMP recv audio (8) csid=4 timestamp=24323 mlen=338 msid=1 nbufs=1 real_mlen=338
2023/07/21 19:33:31 [debug] 20015#20015: *3 ngx_rtmp_kmp_av: no context
2023/07/21 19:33:31 [debug] 20015#20015: *3 recv: eof:0, avail:4984
2023/07/21 19:33:31 [debug] 20015#20015: *3 recv: fd:3 1525 of 1525
2023/07/21 19:33:31 [debug] 20015#20015: *3 recv: avail:3459
2023/07/21 19:33:31 [debug] 20015#20015: *3 recv: eof:0, avail:3459
2023/07/21 19:33:31 [debug] 20015#20015: *3 recv: fd:3 3459 of 4104
2023/07/21 19:33:31 [debug] 20015#20015: *3 recv: avail:0
2023/07/21 19:33:31 [debug] 20015#20015: *3 recv: eof:0, avail:0
2023/07/21 19:33:31 [debug] 20015#20015: timer delta: 55
2023/07/21 19:33:31 [debug] 20015#20015: worker cycle
2023/07/21 19:33:31 [debug] 20015#20015: epoll timer: 18
2023/07/21 19:33:31 [debug] 20015#20015: epoll: fd:3 ev:0001 d:000055A21DEA76C0
2023/07/21 19:33:31 [debug] 20015#20015: *3 recv: eof:0, avail:-1
2023/07/21 19:33:31 [debug] 20015#20015: *3 recv: fd:3 645 of 645
2023/07/21 19:33:31 [debug] 20015#20015: *3 recv: avail:352
2023/07/21 19:33:31 [debug] 20015#20015: *3 recv: eof:0, avail:352
2023/07/21 19:33:31 [debug] 20015#20015: *3 recv: fd:3 352 of 4097
2023/07/21 19:33:31 [debug] 20015#20015: *3 recv: avail:0
2023/07/21 19:33:31 [debug] 20015#20015: *3 RTMP recv video (9) csid=6 timestamp=24343 mlen=8560 msid=1 nbufs=3 real_mlen=8560
2023/07/21 19:33:31 [debug] 20015#20015: *3 ngx_rtmp_kmp_av: no context
2023/07/21 19:33:31 [debug] 20015#20015: *3 recv: eof:0, avail:0
2023/07/21 19:33:31 [debug] 20015#20015: timer delta: 8
2023/07/21 19:33:31 [debug] 20015#20015: worker cycle
2023/07/21 19:33:31 [debug] 20015#20015: epoll timer: 10
2023/07/21 19:33:31 [debug] 20015#20015: timer delta: 10
2023/07/21 19:33:31 [debug] 20015#20015: *3 event timer del: 3: 7260324162

I made some changes to the codec and attempted the following ffmpeg command:

ffmpeg -re -i rtmp://10.0.0.21:1935/stream/live  -c:v libx264 -c:a aac -f flv rtmp://206.75.162.204/ive/ch1_s1

To check for any codec-related issues, we tested the same setup with Wowza and Nimble media servers, and both worked without any problems.

However, with the media-framework, we are facing difficulties as the stream is not working as expected.

Is there any mistake we have done? with media-framework, it's not working.

Thank you in advance.
