### ISSUE TITLE
Request for RTMP Authentication

### ISSUE THREAD

**Issue by 5centscdn** [kaltura/media-framework#171]
Hello there,

We are currently exploring ways to enhance security and protect our media content when utilizing the Media Framework. To achieve this, we would like to implement RTMP authentication for our stream publishing. We were wondering if you could provide us with guidance or documentation on how to set up RTMP authentication with the Media-Framework.

If there is a demo or sample controller.php available that demonstrates RTMP authentication implementation, we would greatly appreciate access to it. This would allow us to perform thorough testing and gain a better understanding of the integration process.

We hope to hear from you soon! Thank you.

**Comment by erankor** [comment]
If you are using the sample controller.php, there's this TODO comment there - `add some authentication logic here`. This code runs when the RTMP module gets an RTMP `connect` message. You can see all fields that you get here - https://github.com/kaltura/media-framework/tree/master/nginx-rtmp-kmp-module#kmp_ctrl_connect_url. 
The logic you need to implement, depends on your application flow. For example, in our system, the RTMP URL is something like - `rtmp://{video id}.publish.kaltura.com:1935/live?t={authentication token}`
So, we parse the `tc_url` param that we get in the connect message, to extract the video id and the authentication token. We pull the authentication token of the specific video from the database, and check if it matches the parameter on the request. If they don't match or the video id is not found, the controller returns an error, and the RTMP connection is dropped.
