### ISSUE TITLE
Optimizing Transcoding Workflow: Request for Direct RTMP Stream Pulling from Media Framework

### ISSUE THREAD

**Issue by 5centscdn** [kaltura/media-framework#172]
Hello there,
Here is our scenario: We have an FFmpeg cluster for live transcoding. Currently, we are pulling an HLS stream from the media framework, transcoding the streams, and then publishing them back to the media framework using FFmpeg. This process introduces a delay in the streaming. Is there an option available to directly pull an RTMP stream from the media framework for the purpose of transcoding?

**Comment by erankor** [comment]
RTMP-pull is not supported, but RTMP-push is supported. You can check out the comment near the `$rtmpOutUrl` variable in the sample controller implementation. 
Another option is to use our transcoder implementation, which is also based on ffmpeg, but is integrated with the other components, for example, it uses the KMP protocol for input / output.
