### ISSUE TITLE
MGPEGTS -> KMP -> RTMP, do I need channel_id and track_id?

### ISSUE THREAD

**Issue by streamingsystems** [kaltura/media-framework#188]
Hi,

I am using your controller.php as an example: 

https://github.com/kaltura/media-framework/blob/master/conf/controller.php

In my case I am just going from MPEGTS -> KMP -> RTMP. 

As such, when I return the array from the controller, in my use-case the channel_id, and track_id seem to be not needed/not applicable.

Using your example response: 

$params = array(
    'code' => 'ok',
    'channel_id' => $channelId, // can I remove this?
    'track_id' => $trackId,  // can I remove this?
    'upstreams' => $upstreams,
);

Can I just return code 'ok' and the RTMP information from your getRtmpOutUpstream() function and omit the channel_id and track_id? 

Thanks!

-Rob

**Comment by erankor** [comment]
Hi, the `channel_id` and `track_id` fields are both required - 
https://github.com/kaltura/media-framework/tree/master/nginx-kmp-out-module#response-fields
They are used to identify the incoming media track - you will get an error if you don't send them.
But, if you don't need this functionality, you can probably just send some fixed values. As far as I remember, these modules do not enforce the uniqueness of these identifiers (unlike nginx-live-module, for example, which will not accept multiple inputs with the same channel_id+track_id)

**Comment by streamingsystems** [comment]
Got it, so in my situation where I am just going from KMP to RTMP I am thinking I set channel_id=1 and track_id = 1 for all of the streams?



From: erankor ***@***.***>
Date: Saturday, January 27, 2024 at 2:32 PM
To: kaltura/media-framework ***@***.***>
Cc: streamingsystems ***@***.***>, Author ***@***.***>
Subject: Re: [kaltura/media-framework] MGPEGTS -> KMP -> RTMP, do I need channel_id and track_id? (Issue #188)

Hi, the channel_id and track_id fields are both required -
https://github.com/kaltura/media-framework/tree/master/nginx-kmp-out-module#response-fields
They are used to identify the incoming media track - you will get an error if you don't send them.
But, if you don't need this functionality, you can probably just send some fixed values. As far as I remember, these modules do not enforce the uniqueness of these identifiers (unlike nginx-live-module, for example, which will not accept multiple inputs with the same channel_id+track_id)

**Comment by erankor** [comment]
Yes, I think you can probably just set them to some const, but it will be better to put a real identifier there, because then if there's some error, you will at least know which channel is affected. As for the track, I think it will also be a good idea to at least distinguish between video and audio, for example "v" vs "a".
The ids can be any alpha-numeric string, up to 32 chars.
