### ISSUE TITLE
srt_listen_callback failed

### ISSUE THREAD

**Issue by streamingsystems** [kaltura/media-framework#189]
Hi,

I followed your steps to build on ubuntu and it seems like it worked great. 

When I launch Nginx (as root) I am seeing this in the logs, any idea what might cause it?

<img width="889" alt="2024-01-29_15-33-38" src="https://github.com/kaltura/media-framework/assets/59889605/15d2fe05-cb1f-4072-886d-5d6861f10a14">

**Comment by streamingsystems** [comment]
I turned on debug and it shows a little more information: 

<img width="939" alt="image" src="https://github.com/kaltura/media-framework/assets/59889605/67399e2c-8473-4b7a-88c5-c89c92d4f4cf">

**Comment by streamingsystems** [comment]
Also, it looks like based on the code when it fails, there is a break, which breaks out of the while but then it hits the end of the function and says it was success and returns NGX_OK when possible it should not break and instead return NGX_ERROR; right when the error is hit?

` /* wait until the thread initializes */

    for (i = 0; ; i++) {

        if (i >= 50) {
            ngx_log_error(NGX_LOG_ALERT, cycle->log, 0,
                "ngx_srt_thread_create: "
                "timed out waiting for thread to start");
            return NGX_ERROR;
        }

        if (*ngx_srt_threads > 0) {
            break;
        }

        if (*ngx_srt_threads < 0) {
            ngx_log_error(NGX_LOG_ALERT, cycle->log, err,
                "ngx_srt_thread_create: thread failed to initialize");
            break;
        }

        ngx_msleep(100);
    }

    ngx_log_error(NGX_LOG_INFO, cycle->log, err,
        "ngx_srt_thread_create: thread initialized successfully");

    return NGX_OK;`

**Comment by streamingsystems** [comment]
I was thinking maybe this had to do with my local environment so I create a brand new Ubuntu instance on Amazon and followed your steps exactly. When I started nginx I got the same errors in the log. It seems that the nginx module is having trouble communicating with the SRT API.

**Comment by erankor** [comment]
I think something changed in libsrt... the error you are getting is -
```
"Operation not supported: Cannot do this operation on a CONNECTED socket", // MN_ISCONNECTED = 2
```

Try to move this block in ngx_str_connection.c -
```
    sls = ngx_pcalloc(cycle->pool, sizeof(ngx_srt_listening_t));
    if (sls == NULL) {
        ngx_log_error(NGX_LOG_NOTICE, cycle->log, 0,
            "ngx_srt_listen: ngx_srt_listen: alloc session failed");
        return NGX_ERROR;
    }

    if (srt_listen_callback(ss, ngx_srt_listen_callback, sls) != 0) {
        serr = srt_getlasterror(&serrno);
        ngx_log_error(NGX_LOG_EMERG, cycle->log, serrno,
            "ngx_srt_listen: srt_listen_callback() failed %d", serr);
        return NGX_ERROR;
    }
```
to be before the call to srt_bind_acquire.

**Comment by streamingsystems** [comment]
It looks like that did it. Do you want me to create a PR or do you want to swap the code and commit? Later in the week we are going to build on the production boxes so would like to pull down the changed code from the repo if possible.

From: erankor ***@***.***>
Date: Tuesday, January 30, 2024 at 12:55 AM
To: kaltura/media-framework ***@***.***>
Cc: streamingsystems ***@***.***>, Author ***@***.***>
Subject: Re: [kaltura/media-framework] srt_listen_callback failed (Issue #189)

I think something changed in libsrt... the error you are getting is -

"Operation not supported: Cannot do this operation on a CONNECTED socket", // MN_ISCONNECTED = 2

Try to move this block in ngx_str_connection.c -

    sls = ngx_pcalloc(cycle->pool, sizeof(ngx_srt_listening_t));

    if (sls == NULL) {

        ngx_log_error(NGX_LOG_NOTICE, cycle->log, 0,

            "ngx_srt_listen: ngx_srt_listen: alloc session failed");

        return NGX_ERROR;

    }



    if (srt_listen_callback(ss, ngx_srt_listen_callback, sls) != 0) {

        serr = srt_getlasterror(&serrno);

        ngx_log_error(NGX_LOG_EMERG, cycle->log, serrno,

            "ngx_srt_listen: srt_listen_callback() failed %d", serr);

        return NGX_ERROR;

    }

to be before the call to srt_bind_acquire.

**Comment by erankor** [comment]
Opened https://github.com/kaltura/nginx-srt-module/pull/36
