### ISSUE TITLE
Support for video manipulations or raw video input

### ISSUE THREAD

**Issue by Ivan114654** [kaltura/media-framework#197]
1. If input of the media framework is RTMP is it possible inside the media framework to somehow change video stream before publishing to KMP or during transcoding using ffmpeg standard filters? For example if I want to add a logo to the stream.
2. If input is a raw video stream, is it possible to transcode it directly to KMP to avoid losses and delays on additional transcoding it to RTMP?

**Comment by erankor** [comment]
1. I'm not an expert on the transcoder, but looking at the code, it seems to support only scale and framestep (https://github.com/kaltura/media-framework/blob/master/transcoder/transcode/transcode_session.c#L168)
2. Some kind of container is required - either RTMP or MPEG-TS. But, assuming you have a codec that is supported by these containers (e.g. h264), the packaging does not require transcoding - there is no quality degradation, and it's light in terms of resource utilization
