### ISSUE TITLE
Dynamic SRT passphrases

### ISSUE THREAD

**Issue by jpluijmers** [kaltura/media-framework#209]
Hi, first of all thanks for the great work on this new way of doing live streaming. We've outgrown Wowza for a while now. 

While designing this solution I keep getting back to one problem I just can't quite figure out: how can I provide a passphrase for each separate stream id. This is of course to provide some kind of access control and insulation for each different client that might be using the system. 

**The dilemma**: both the _srt_passphrase_ and _srt_proxy_passphrase_ have to be defined at startup. This means:
1. I have to provision tasks (including the ingest) for each stream separately and pass the secret here.
2. Use a "company wide" passphrase, which is no kind of secret at all. 

I've read the SRT spec and unfortunately it is in my - rookie - opinion impossible to create a dumb proxy since all protocol headers are encrypted. Meaning the proxy will always need to read the stream to maintain proper state with the sender.

**The question**: Are there any viable options to investigate here or is this folly and should I just go with option nr1. The option I've thought up is implement the handshake protocol, since the StreamId is in the HELLO and fetch the passphrase and then hand over the rest to libsrt.  

I would appreciate your views and experience on this :)

**Comment by erankor** [comment]
Hi, what you can do is encrypt the passphrase using a key stored on your server, and embed it in the SRT stream_id. 
Then, use a combination of the `srt` directives `map` / `set_decode_base64url` / `set_aes_decrypt` to extract the passphrase from the stream_id to an nginx variable.
Something like this -
```
srt {
	...
	
    map $stream_id $encoded_passphrase {
        ~passphrase=(?P<result>[-A-Za-z0-9+/=]+) $result;
    }

    set_decode_base64url $encrypted_passphrase $encoded_passphrase;
    set_aes_decrypt      $passphrase AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA= AAAAAAAAAAAAAAAAAAAAAA== $encrypted_passphrase;

	server {
		...
		passphrase $passphrase;
	}
}
```

**Comment by jpluijmers** [comment]
Thanks for your swift reply erankor, that is a giant leap in the right direction! It provides a neat way to avoid the messy provisioning by using a trusted key encryption key. 

The last thing to solve is then: the solution above validates you to open a socket to the ingest but does not limit the stream_id you can stream to. The nicest way I can think of is to solve this in the kmp/connect call, but the passphrase is not sent on the call to do the validation. Should I wrap both in de aes string and override it in the proxy_stream_id?

Thanks for your help!

**Comment by erankor** [comment]
If you are using a configuration like [this one](https://github.com/kaltura/media-framework/tree/master/nginx-mpegts-kmp-module#sample-configuration), to propagate the SRT stream id, you will get the stream id on both the connect and publish messages. 
So, you can just use two fields on the stream id - one will contain the encrypted passphrase, and the other will be used for authentication.

**Comment by jpluijmers** [comment]
Thank you for your feedback, I intend to do a test with this coming summer.
